Draft: activate powershell signing for install script
mondoohq/client pull request #225
Opened 2022-12-25 13:04 UTC by atomic111

Signed-off-by: Patrick Münch <patrick.muench1111@gmail.com>

2022-12-26 15:36 UTC, chris-rock commented
Prior to PowerShell 7.2, the script must be saved using ASCII or UTF8NoBOM encoding. PowerShell 7.2 and higher supports signed scripts for any encoding format. We should add a check that it is UTF8NoBOM

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.3#sign-a-script

I added a few lines to enforce encoding that I learned from here https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom

2022-12-26 15:38 UTC, chris-rock approved these changes
Thank you @atomic111 for this improvement

2022-12-26 15:40 UTC, chris-rock commented
I rebased this PR on #226 to see if it turns green. Lets merge 226 first then we can rebase this on master.

2022-12-26 21:17 UTC, chris-rock requested changes

2022-12-26 21:17 UTC, chris-rock commented on install.ps1
> +# SIG # Begin signature block
Since the signature should be added by the github action, I would like to keep it out of the PR

2022-12-26 21:17 UTC, chris-rock commented on install.ps1
> +  # if((Get-ExecutionPolicy) -gt 'RemoteSigned' -or (Get-ExecutionPolicy) -eq 'ByPass') {
Let's completely remove that part since we do not need it anymore once signing is enabled.

2022-12-26 21:17 UTC, chris-rock commented on .github/workflows/sign_powershell.yml
> +          $filename = '.\install.ps1'
This needs to be `install.ps1`, otherwise pwsh under linux creates a file ".\\install.ps1"

2022-12-26 22:02 UTC, chris-rock commented
<img width="976" alt="Screenshot 2022-12-26 at 22 43 17" src="https://user-images.githubusercontent.com/1178413/209585605-17b656cb-61d0-48b4-949b-2545e0cc3070.png">
<img width="982" alt="Screenshot 2022-12-26 at 22 40 35" src="https://user-images.githubusercontent.com/1178413/209585607-d750ba80-b799-4275-9e30-3b355914e769.png">

I tested the installation with the `sign-test` branch and it works like a charm.

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/mondoohq/client/sign-test/install.ps1')); Install-Mondoo
```

2022-12-26 22:02 UTC, chris-rock approved these changes

2022-12-27 13:02 UTC, atomic111 commented on .github/workflows/sign_powershell.yml
> +          # sign install.sh and ensure proper encoding as UTF8 NoBOM
```suggestion
          # sign download.sh and ensure proper encoding as UTF8 NoBOM
```

2022-12-27 13:02 UTC, atomic111 commented on .github/workflows/sign_powershell.yml
> +          # sign install.sh and ensure proper encoding as UTF8 NoBOM
```suggestion
          # sign download.sh and ensure proper encoding as UTF8 NoBOM
```

2022-12-27 13:06 UTC, atomic111 commented
@chris-rock thanks for your help

2022-12-27 13:06 UTC, merged